
@BASE_URL = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTU4OTMwOTM3MWFjNTQ2ZDk4NDRkNzUiLCJpYXQiOjE3Njk0MzU1NzIsImV4cCI6MTc2OTUyMTk3Mn0.wWwTrYBkiaqxGpUYgxp7AUHmyid6xv3kaUILa6yhd7k

###
POST {{BASE_URL}}/auth/login 
Content-Type : application/json

{
  "email": "duy@gmail.com", 
  "password" : "123456"
}

###
POST {{BASE_URL}}/auth/register 
Content-Type : application/json

{
  "fullName" : "phung van duy",
  "email": "phung@gmail.com", 
  "password" : "123456" , 
  "passwordConfirm" : "123456"
}

###
POST {{BASE_URL}}/auth/logout 
Content-Type : application/json


###
get {{BASE_URL}}/chat/rooms?status=accepted
Content-Type : application/json
Authorization: Bearer {{token}}

###
GET  {{BASE_URL}}/chat/room/6971fc1fb8c530cd5f358c40 
Content-Type : application/json
Authorization: Bearer {{token}}

// api_user. 
###
GET  {{BASE_URL}}/users 

###
GET {{BASE_URL}}/users/friend-accepts

###
GET {{BASE_URL}}/users/friends

// end api_user. 

// api_room  
###
post {{BASE_URL}}/room/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "titleRoom" : "testRoom",
  "members" : [ 
    "6965c572cad48fa15af26fbe",
    "696229443a2254e15056776b"
  ]
}

### 
GET {{BASE_URL}}/room/detail/6971fc1fb8c530cd5f358c40
Authorization: Bearer {{token}}

###
POST  {{BASE_URL}}/room/remove-member/6970e3eb9f810f7b919c7063
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "removeMemberID" : "6965c572cad48fa15af26fbe"
}

###
POST  {{BASE_URL}}/room/add-member/6970e3eb9f810f7b919c7063
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "newMemberIDs" : "6965c572cad48fa15af26fbe"
}

###
POST  {{BASE_URL}}/room/delete/6970e3eb9f810f7b919c7063
Content-Type: application/json
Authorization: Bearer {{token}}

// end api_room    


###
POST {{BASE_URL}}/upload/files 
Content-Type: application/json

{
  "test" : "5"
}