
@BASE_URL = http://localhost:5000

###
POST {{BASE_URL}}/auth/login 
Content-Type : application/json

{
  "email": "duy@gmail.com", 
  "password" : "123456"
}

###
POST {{BASE_URL}}/auth/logout 
Content-Type : application/json


###
get {{BASE_URL}}/chat/rooms
Content-Type : application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTU4OTMwOTM3MWFjNTQ2ZDk4NDRkNzUiLCJpYXQiOjE3Njg4NzM3NTUsImV4cCI6MTc2ODk2MDE1NX0.rQ7aqRAJ12XPMEN2om6dJ7ASKIvpPB8rE7gyIA_LcSk


###
GET  {{BASE_URL}}/chat/room/234234234322 
Content-Type : application/json